# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 聚看点

on:
  workflow_dispatch:
  schedule:
     - cron: '0,30 * * * *'
  watch:
    types: started
  repository_dispatch:
        types: jkd    
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      JKD_COOKIE: ${{ secrets.JKD_COOKIE }}
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
          
      - name: '运行 【聚看点】'
        if: env.JKD_COOKIE
        run: |
          node jkd.js
        env:
          JKD_COOKIE: ${{ secrets.JKD_COOKIE }}  