name: Delete Workflow Runs
on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 0-16,22-23 * * *'
  watch:
    types: started
  repository_dispatch:
    types: Delete-Workflow

jobs:
  del_runs:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.token }}
          repository: ${{ github.repository }}
          retain_days: 2
