name: Delete Workflow Runs
on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 0-16,22-23 * * *'
  watch:
    types: started
  repository_dispatch:
    types: Delete-Workflow
    
jobs:
  sync:
    runs-on: ubuntu-18.04
    #if: github.repository == 'RikudouPatrickstar/jd_scripts'
    if: github.event.repository.owner.id == github.event.sender.id
    timeout-minutes: 2
    steps:
    - name: Delete Workflow Runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 1
        keep_minimum_runs: 0
